name: phage-flores
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - python=3.10
  - pip
  - jupyterlab
  - notebook

  # Download
  - wget
  - curl

  # QC
  - fastqc
  - multiqc

  # Trimming/filtering
  - fastp

  # Assembly
  - megahit

  # Sequence utilities
  - seqkit

  # General
  - pandas
  - matplotlib
  - biopython
